### ISSUE TITLE
Could not load driver (undefined method `driver_name' for ODBC:Module)

### ISSUE THREAD

**Issue by tsujigiri** [erikh/ruby-dbi#11]
Hi,

I have a problem, which seems to be related to the way I require `dbi` and/or `ruby-odbc`.
Using Bundler I get this error:

```
Could not load driver (undefined method `driver_name' for ODBC:Module)
/usr/lib/ruby/gems/1.9.1/gems/dbi-0.4.5/lib/dbi.rb:318:in `rescue in load_driver'
/usr/lib/ruby/gems/1.9.1/gems/dbi-0.4.5/lib/dbi.rb:242:in `load_driver'
/usr/lib/ruby/gems/1.9.1/gems/dbi-0.4.5/lib/dbi.rb:160:in `_get_full_driver'
/usr/lib/ruby/gems/1.9.1/gems/dbi-0.4.5/lib/dbi.rb:145:in `connect'
```

When I just fire-up irb and require dbi and odbc_utf8 myself, it works.

I addressed that in more detail [here](http://stackoverflow.com/questions/10481881/dbi-ruby-odbc-fails-with-bundler-involved).

I tried Ruby 1.9.2 and 1.9.3.

_edit_: The irb way works in ruby 1.9.3, but not in 1.9.2.
